### PR TITLE
fix: detect multi-line values if they contain a `=` sign

### LINKED ISSUE #460: Doesn't detect multi-line values if they contain a `=` sign
Example:

```env
MULTILINE="{
    'key': 'value='
}"
```

Result:

```
Checking .env
.env:1 QuoteCharacter: The value has quote characters (', ")
.env:2 IncorrectDelimiter: The 'key': 'value key has incorrect delimiter
.env:2 LeadingCharacter: Invalid leading character detected
.env:2 LowercaseKey: The 'key': 'value key should be in uppercase
.env:2 QuoteCharacter: The value has quote characters (', ")
.env:2 UnorderedKey: The 'key': 'value key should go before the MULTILINE key
.env:3 KeyWithoutValue: The }" key should be with a value or have an equal sign
.env:3 LeadingCharacter: Invalid leading character detected

Found 8 problems
```

### PR DESCRIPTION
**Pull request by DDtKey**
This one is questionable. 
I've implemented it in standard way for `env` libraries and `bash`, but maybe there is a more suitable approach for the linter 🤔  (As I already mentioned in [previous PR's ](https://github.com/dotenv-linter/dotenv-linter/pull/453#discussion_r767277007))
It works well, but I mean it makes the `QuoteCharacterChecker` a little useless.

Closes #460

#### ✔ Checklist:

- [X] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [X] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [X] Tests for the changes have been added (for bug fixes / features);
- [ ] Docs have been added / updated on the [dotenv-linter.github.io](https://github.com/dotenv-linter/dotenv-linter.github.io) (for bug fixes / features).

### CODE REVIEW

**Comment by mgrachev** [comment]
> It works well, but I mean it makes the `QuoteCharacterChecker` a little useless.

Can you give an example of this?

**Comment by DDtKey** [comment]
> > It works well, but I mean it makes the `QuoteCharacterChecker` a little useless.
> 
> Can you give an example of this?

See changes in `complicated.env` - that's consequences of this changes.
Any non-escaped quote-char in `env` tells us that this is multi-line start (you can check this right in the shell)

For example, here will be one multi-line value instead of two `QuoteCharacter` warnings  (as it was before)
```sh
KEY="VALUE
KEY2=VALUE2"
```

The only time we can meet his warning is if there was no closing quote to the end of the file.
For example, in this case we'll receive one `QuoteCharacter` warning (1 line)
```sh
KEY="VALUE
KEY2=VALUE2
```

In general, it seems to me to be correct 🤔

**Comment by DDtKey** [comment]
> The only time we can meet his warning is if there was no closing quote to the end of the file. For example, in this case we'll receive one `QuoteCharacter` warning (1 line)

I've updated test with this case

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
Thanks a lot 🔥🔥🔥

**Pull request merged**
