### PR TITLE
ci: use correct archlinux image

### LINKED ISSUE #430: AUR release failed
@mstruebing Hi 👋 Could you take a look at this?
https://github.com/dotenv-linter/dotenv-linter/runs/2783455884?check_suite_focus=true

### PR DESCRIPTION
**Pull request by mstruebing**
This should fix the issue.
Should we retrigger that pipeline?

closes #430

#### ✔ Checklist:

- [x] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [ ] Tests for the changes have been added (for bug fixes / features);
- [ ] Docs have been added / updated on the [dotenv-linter.github.io](https://github.com/dotenv-linter/dotenv-linter.github.io) (for bug fixes / features).

### CODE REVIEW

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@mstruebing Thank you 👍

Can you run this process manually?

**Comment by mstruebing** [comment]
Will do!

**Comment by mstruebing** [comment]
Done: https://aur.archlinux.org/packages/dotenv

**Comment by mgrachev** [comment]
Thank you ❤️

**Pull request merged**
