### PR TITLE
Add misspell action

### LINKED ISSUE #301: Add action-misspell
Add `action-misspell` to correct commonly misspelled English words in source files.

Link:
https://github.com/reviewdog/action-misspell

### PR DESCRIPTION
**Pull request by PurpleMyst**
Resolves #301

### CODE REVIEW

**Review by mstruebing — CHANGES_REQUESTED** [review]
Hey @PurpleMyst great PR, thank you :rocket: 

Could you please add your changes to the `CHANGELOG.md`-file?

**Comment by PurpleMyst** [comment]
Sure thing, I did in 371c3c3d33b3bffaab8bd7abec326ae8239c700b.

**Review by mstruebing — APPROVED** [review]
Great, thank you very much :handshake:

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@PurpleMyst Thank you for your contribution! 👍

🙏 If it’s not difficult for you, please support the project - click on the star on GitHub ⭐️

**Pull request merged**
