### PR TITLE
ci: add hadolint action to workflows/lints.yml (#380)

### PR DESCRIPTION
**Pull request by iovanom**
Add hadolint to lints workflows for check Dockerfile. Issue (#380)

#### ✔ Checklist:

- [x] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [x] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [ ] Tests for the changes have been added (for bug fixes / features);
- [ ] Docs have been added / updated on the [dotenv-linter.github.io](https://github.com/dotenv-linter/dotenv-linter.github.io) (for bug fixes / features).

### CODE REVIEW

**Comment by mgrachev** [comment]
@iovanom 👋 Thank you for your contribution 👍

You missed this item:
> - [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);

**Comment by iovanom** [comment]
> @iovanom  Thank you for your contribution 
> 
> You missed this item:
> 
> > * [ ]  This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);

Should I add the CI changes to CHANGELOG ?

**Comment by mgrachev** [comment]
> > @iovanom  Thank you for your contribution
> > You missed this item:
> > > * [ ]   This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
> 
> Should I add the CI changes to CHANGELOG ? I didn't find any CI change in CHANGELOG.md

Yes, you should. E.g.:
> Add action-yamllint #317 (@vk26)

**Comment by iovanom** [comment]
> > > @iovanom  Thank you for your contribution
> > > You missed this item:
> > > > * [ ]    This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
> > 
> > 
> > Should I add the CI changes to CHANGELOG ? I didn't find any CI change in CHANGELOG.md
> 
> Yes, you should. E.g.:
> 
> > Add action-yamllint #317 (@vk26)

Done ;)

**Review by mgrachev — DISMISSED** [review]

**Comment by mgrachev** [comment]
@iovanom Thank you for your help 👍

**Pull request merged**
