### PR TITLE
Adds additional test for LineEntry.get_value

### LINKED ISSUE #292: Add additional test for LineEntry.get_value
Add an additional test for [LineEntry.get_value](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/line_entry.rs#L38) to make sure it works correctly with quotes:
```env
FOO='BAR'
FOO="BAR"
```

### PR DESCRIPTION
**Pull request by vvkpd**
## Summary of change

adds additional test for **get_value** method which is in **Line_entry.rs**

## Related issue

Closes #292 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

  - [x] Ensure code changes pass all tests

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Resolved any merge conflicts

### CODE REVIEW

**Comment by mgrachev** [comment]
@vvkpd 👋 Thank you for your contribution! 🎉

Please add this PR to CHANGELOG.md (at the top of the `Changed` list).

**Comment by vvkpd** [comment]
Hey @mgrachev, I made the changes please take a look and review it.
Thanks

**Comment by vvkpd** [comment]
Hey @mgrachev,
Sorry to interrupt you again!
Could you please add **hacktoberfest-accepted** label in my raised pr?

Background: 
Screenshot 2020-10-06 at 1 52 48 PM
Thanks

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@vvkpd Thank you! 👍

🙏 If it’s not difficult for you, please support the project - click on the star on GitHub ⭐️

**Pull request merged**
