### PR TITLE
added .env explaination

### PR DESCRIPTION
**Pull request by henryboisdequin**
For #362

#### ✔ Checklist:

- [x] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);

Is the CHANGELOG.md change necessary?

### CODE REVIEW

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@henryboisdequin 👋 Thank you for your contribution! 👍

🙏 If it’s not difficult for you, please support the project - star on GitHub ⭐️

**Comment by vi** [comment]
This explanation does help a bit, but I'm still feeling a bit out of the loop.

> A .env file contains all your project's environment variables. 

The ones like `PATH` or `LD_LIBRARY_PATH`? Or some other config files, whose entries named "environment variables" without being actual OS-level environment variables (like a Java property files)?

> It's usually stuff you don't want to share like your API keys or passwords.

So is it probably about some web or backend projects? I remember CGI and environment variables being connected somehow.

> They're stored in a key, value pair format, like this: `username=dotenv-linter`.

This lone line does not help much. I'd suggest instead to link to something that describes those dotenv files format and usage in some specific type of projects (searching around suggests it's for NodeJS, Python or Docker Compose things), with a bigger example containing variables names used in a real project.

---

Also while we are at README improvement, I'd put an example of a broken dotenv files in "Available checks" section, showing multiple (not necessarily all) problems that are detected by the linter, maybe with a fixed version along.

Something like this:

```
IP = 127.0.0.1 # extra whitespace
 port=8080   # lower case, leading whitespace
CERT-FILE="qqq.pem" # dash, excessive quoting
```

showing that it is getting turned to

```
IP=127.0.0.1
PORT=8080
CERT_FILE=qqq.pem
```

(maybe with more appropriate, realistic things instead of `IP`, `PORT` and `CERT_FILE`). 

[Comparison feature](https://dotenv-linter.github.io/#/usage/compare) is also notable enough to be showed off in the beginning of README (e.g. using the snipped already available in the linked documentation page).

**Comment by mgrachev** [comment]
@vi I have just updated the explanation of `.env` files and added some links.

In addition, we moved all the documentation and examples from the README.md file to our site https://dotenv-linter.github.io.

**Comment by vi** [comment]
With the new links the introduction README section is now more clear and helpful.

**Comment by mgrachev** [comment]
> With the new links the introduction README section is now more clear and helpful.

Thank you for your suggestions 👍

**Pull request merged**
