### PR TITLE
Add windows publishing to release workflow

### PR DESCRIPTION
**Pull request by DDtKey**
How do you look at adding a build for Windows to release builds?
I think this could be useful, or at least not superfluous.

I created a simple workflow job creating a `zip` archive with an executable file(`.exe`) for the target platform.
Perhaps in the future for these purposes it is worth thinking about `msi`.

#### ✔ Checklist:

- [x] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [X] Docs have been added / updated (for bug fixes / features).

### CODE REVIEW

**Comment by mgrachev** [comment]
@DDtKey It's a good idea! Thank you!

But, I'm not sure if dotenv-linter works on Windows or not.

**Comment by DDtKey** [comment]
> @DDtKey It's a good idea! Thank you!
> 
> But, I'm not sure if dotenv-linter works on Windows or not.
> I can't check it because I don't have any computers on Windows.

I think it should work.
But definitely, I need to check, today I will use one of my laptops, check dotenv-linter for Windows.

**Comment by mgrachev** [comment]
Thank you!
I think we should wait with these changes until the next release after v2.0.0.
I will open an issue to keep all things related with Windows support in one place.

**Comment by mgrachev** [comment]
@DDtKey I will be glad to discuss any your suggestions there https://github.com/dotenv-linter/dotenv-linter/issues/212

**Comment by DDtKey** [comment]
> @DDtKey I will be glad to discuss any your suggestions there #212

Thank you! I will gladly share the results of the tests there.

**Comment by DDtKey** [comment]
It would be nice to configure, besides the portable archive (`zip`), the `msi` installer as an additional step in the job.
To do this, you can use _WIX-Tools_ as far as I know, and they [come with a Windows environment for github.](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#wix-tools)

Unfortunately, I'm not strong at this, so maybe someone will also help.

**Comment by mgrachev** [comment]
What do you think about using [Scoop](https://scoop.sh) instead of `msi`?

**Comment by DDtKey** [comment]
> What do you think about using [Scoop](https://scoop.sh) instead of `msi`?

It looks really more user friendly, a good idea! :rocket: 

In addition, you can consider the recently released [WinGet from Microsoft](https://docs.microsoft.com/en-us/windows/package-manager/winget/), which in fact is an alternative to [AppGet](https://appget.net/).

**Comment by DDtKey** [comment]
At the moment, WinGet doesn't support install `.zip` archives, but exists [issue](https://github.com/dotenv-linter/dotenv-linter/raw/master/) and when (if?) the feature is added, we can create additional manifest.

For now, I have added Scoop manifest to repository with auto-update configuration.

**Comment by mgrachev** [comment]
I've added a separate repository to store the Scoop manifest - https://github.com/dotenv-linter/scoop/pull/1

**Comment by DDtKey** [comment]
> I've added a separate repository to store the Scoop manifest - [dotenv-linter/scoop#1](https://github.com/dotenv-linter/scoop/pull/1)

Thanks a lot! I like this option too :rocket:

**Comment by mgrachev** [comment]
@DDtKey You have done excellent work! 🚀 Thank you so much for your help with Windows support! ❤️

I'd like to invite you to join the @dotenv-linter organization on GitHub. What do you think about it?

**Comment by DDtKey** [comment]
> @DDtKey You have done excellent work! rocket Thank you so much for your help with Windows support! heart
> 
> I'd like to invite you to join the @dotenv-linter organization on GitHub. What do you think about it?

Thank you, I don't mind and will be happy to continue to participate in the development of `dotenv-linter` anyway! :blush:

**Comment by mgrachev** [comment]
> Thank you, I don't mind and will be happy to continue to participate in the development of `dotenv-linter` anyway! 😊

Cool! I've sent you invitation 🦀

**Pull request merged**
