### PR TITLE
Add check_output function for integration tests

### PR DESCRIPTION
**Pull request by Anthuang**
This PR adds a `check_output` function for integration tests, and refactors current tests to use it. The added function is made to be similar to `fix_output`, which already exists.

Resolves: #293

#### ✔ Checklist:

~- [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);~
~- [ ] Tests for the changes have been added (for bug fixes / features);~
~- [ ] Docs have been added / updated (for bug fixes / features).~

Crossed out the above since this is just an internal improvement. Let me know if there's anything else I should do!

### CODE REVIEW

**Comment by mgrachev** [comment]
@Anthuang 👋 Thank you for your contribution! 🚀

Please add this PR to CHANGELOG.md (at the top of the `Changed` list).

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@Anthuang Thank you! 👍

🙏 If it’s not difficult for you, please support the project - click on the star on GitHub ⭐️

**Comment by Anthuang** [comment]
I'd be happy to! I'm just starting out in Rust and am looking for projects to contribute to. It seems like all the current issues are taken, is there anything else I can help out with?

**Comment by mgrachev** [comment]
> I'd be happy to! I'm just starting out in Rust and am looking for projects to contribute to. It seems like all the current issues are taken, is there anything else I can help out with?

You can take this one https://github.com/dotenv-linter/dotenv-linter/issues/268 😉

**Pull request merged**
